// try catch
try {
  hello();
} catch (error) {
  console.log(error);
}

// ES10
try {
  anotherFn();
} catch {
  console.log("There is an error");
}
